controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    rear_wheels_velocity_controller:
      type: forward_command_controller/ForwardCommandController
    front_steer_position_controller:
      type: forward_command_controller/ForwardCommandController

rear_wheels_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    interface_name: velocity

front_steer_position_controller:
  ros__parameters:
    joints:
      - front_left_wheel_steer_joint
      - front_right_wheel_steer_joint
    interface_name: position
